services:
  odoo:
    build:
      context: .
      dockerfile: odoo/Dockerfile
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      - SERVICE_URL_ODOO_8069
      - HOST=postgresql
      - USER=$SERVICE_USER_POSTGRES
      - PASSWORD=$SERVICE_PASSWORD_POSTGRES
    volumes:
      - odoo-web-data:/var/lib/odoo
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8069"]
      interval: 5s
      timeout: 20s
      retries: 30

  postgresql:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - POSTGRES_DB=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  odoo-web-data:
  postgresql-data:
